// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.12.4
// source: monkey.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "oceanchat.monkey";

/** MSG_UP: Client -> Server message */
export interface MsgUp {
  clientMsgId: string;
  groupId: string;
  msgType: MsgUp_MsgType;
  /** TEXT */
  content: string;
  /** MEDIA */
  url: string;
  width: number;
  height: number;
  size: string;
  format: string;
  duration: number;
  fileName: string;
  extension: string;
  thumbnailUrl: string;
}

export enum MsgUp_MsgType {
  TEXT = 0,
  IMAGE = 1,
  AUDIO = 2,
  FILE = 3,
  UNRECOGNIZED = -1,
}

export function msgUp_MsgTypeFromJSON(object: any): MsgUp_MsgType {
  switch (object) {
    case 0:
    case "TEXT":
      return MsgUp_MsgType.TEXT;
    case 1:
    case "IMAGE":
      return MsgUp_MsgType.IMAGE;
    case 2:
    case "AUDIO":
      return MsgUp_MsgType.AUDIO;
    case 3:
    case "FILE":
      return MsgUp_MsgType.FILE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MsgUp_MsgType.UNRECOGNIZED;
  }
}

export function msgUp_MsgTypeToJSON(object: MsgUp_MsgType): string {
  switch (object) {
    case MsgUp_MsgType.TEXT:
      return "TEXT";
    case MsgUp_MsgType.IMAGE:
      return "IMAGE";
    case MsgUp_MsgType.AUDIO:
      return "AUDIO";
    case MsgUp_MsgType.FILE:
      return "FILE";
    case MsgUp_MsgType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** MSG_UP_ACK: Server -> Client ack */
export interface MsgUpAck {
  clientMsgId: string;
  syncSeqId: string;
  success: boolean;
  errorMessage: string;
  serverTimestamp: string;
}

/** MSG_NOTIFY: Global new message notification */
export interface MsgNotify {
  groupId: string;
  syncSeqId: string;
}

/** AUTH_REQ: Handshake auth request */
export interface AuthReq {
  deviceType: string;
  deviceId: string;
  jwt: string;
  supportedVersions: number[];
}

/** AUTH_ACK: Handshake auth response */
export interface AuthAck {
  userId: string;
}

/** READ_RECEIPT: Cross-device read receipt sync */
export interface ReadReceipt {
  groupId: string;
  syncSeqId: string;
}

/** EXCEPTION_ACK: Global exception response */
export interface ExceptionAck {
  errorCode: number;
  message: string;
  timestamp: string;
  serverSupportedVersions: number[];
}

export const OCEANCHAT_MONKEY_PACKAGE_NAME = "oceanchat.monkey";

function createBaseMsgUp(): MsgUp {
  return {
    clientMsgId: "",
    groupId: "",
    msgType: 0,
    content: "",
    url: "",
    width: 0,
    height: 0,
    size: "0",
    format: "",
    duration: 0,
    fileName: "",
    extension: "",
    thumbnailUrl: "",
  };
}

export const MsgUp: MessageFns<MsgUp> = {
  encode(message: MsgUp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMsgId !== "") {
      writer.uint32(10).string(message.clientMsgId);
    }
    if (message.groupId !== "") {
      writer.uint32(18).string(message.groupId);
    }
    if (message.msgType !== 0) {
      writer.uint32(24).int32(message.msgType);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.url !== "") {
      writer.uint32(42).string(message.url);
    }
    if (message.width !== 0) {
      writer.uint32(48).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(56).int32(message.height);
    }
    if (message.size !== "0") {
      writer.uint32(64).int64(message.size);
    }
    if (message.format !== "") {
      writer.uint32(74).string(message.format);
    }
    if (message.duration !== 0) {
      writer.uint32(80).int32(message.duration);
    }
    if (message.fileName !== "") {
      writer.uint32(90).string(message.fileName);
    }
    if (message.extension !== "") {
      writer.uint32(98).string(message.extension);
    }
    if (message.thumbnailUrl !== "") {
      writer.uint32(106).string(message.thumbnailUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.groupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.msgType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.size = reader.int64().toString();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.format = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.extension = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.thumbnailUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUp {
    return {
      clientMsgId: isSet(object.clientMsgId) ? globalThis.String(object.clientMsgId) : "",
      groupId: isSet(object.groupId) ? globalThis.String(object.groupId) : "",
      msgType: isSet(object.msgType) ? msgUp_MsgTypeFromJSON(object.msgType) : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      size: isSet(object.size) ? globalThis.String(object.size) : "0",
      format: isSet(object.format) ? globalThis.String(object.format) : "",
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : 0,
      fileName: isSet(object.fileName) ? globalThis.String(object.fileName) : "",
      extension: isSet(object.extension) ? globalThis.String(object.extension) : "",
      thumbnailUrl: isSet(object.thumbnailUrl) ? globalThis.String(object.thumbnailUrl) : "",
    };
  },

  toJSON(message: MsgUp): unknown {
    const obj: any = {};
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.groupId !== "") {
      obj.groupId = message.groupId;
    }
    if (message.msgType !== 0) {
      obj.msgType = msgUp_MsgTypeToJSON(message.msgType);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.size !== "0") {
      obj.size = message.size;
    }
    if (message.format !== "") {
      obj.format = message.format;
    }
    if (message.duration !== 0) {
      obj.duration = Math.round(message.duration);
    }
    if (message.fileName !== "") {
      obj.fileName = message.fileName;
    }
    if (message.extension !== "") {
      obj.extension = message.extension;
    }
    if (message.thumbnailUrl !== "") {
      obj.thumbnailUrl = message.thumbnailUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUp>, I>>(base?: I): MsgUp {
    return MsgUp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUp>, I>>(object: I): MsgUp {
    const message = createBaseMsgUp();
    message.clientMsgId = object.clientMsgId ?? "";
    message.groupId = object.groupId ?? "";
    message.msgType = object.msgType ?? 0;
    message.content = object.content ?? "";
    message.url = object.url ?? "";
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.size = object.size ?? "0";
    message.format = object.format ?? "";
    message.duration = object.duration ?? 0;
    message.fileName = object.fileName ?? "";
    message.extension = object.extension ?? "";
    message.thumbnailUrl = object.thumbnailUrl ?? "";
    return message;
  },
};

function createBaseMsgUpAck(): MsgUpAck {
  return { clientMsgId: "", syncSeqId: "0", success: false, errorMessage: "", serverTimestamp: "0" };
}

export const MsgUpAck: MessageFns<MsgUpAck> = {
  encode(message: MsgUpAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientMsgId !== "") {
      writer.uint32(10).string(message.clientMsgId);
    }
    if (message.syncSeqId !== "0") {
      writer.uint32(16).uint64(message.syncSeqId);
    }
    if (message.success !== false) {
      writer.uint32(24).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(34).string(message.errorMessage);
    }
    if (message.serverTimestamp !== "0") {
      writer.uint32(40).int64(message.serverTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientMsgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.syncSeqId = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.serverTimestamp = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpAck {
    return {
      clientMsgId: isSet(object.clientMsgId) ? globalThis.String(object.clientMsgId) : "",
      syncSeqId: isSet(object.syncSeqId) ? globalThis.String(object.syncSeqId) : "0",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
      serverTimestamp: isSet(object.serverTimestamp) ? globalThis.String(object.serverTimestamp) : "0",
    };
  },

  toJSON(message: MsgUpAck): unknown {
    const obj: any = {};
    if (message.clientMsgId !== "") {
      obj.clientMsgId = message.clientMsgId;
    }
    if (message.syncSeqId !== "0") {
      obj.syncSeqId = message.syncSeqId;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.serverTimestamp !== "0") {
      obj.serverTimestamp = message.serverTimestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpAck>, I>>(base?: I): MsgUpAck {
    return MsgUpAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpAck>, I>>(object: I): MsgUpAck {
    const message = createBaseMsgUpAck();
    message.clientMsgId = object.clientMsgId ?? "";
    message.syncSeqId = object.syncSeqId ?? "0";
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    message.serverTimestamp = object.serverTimestamp ?? "0";
    return message;
  },
};

function createBaseMsgNotify(): MsgNotify {
  return { groupId: "", syncSeqId: "0" };
}

export const MsgNotify: MessageFns<MsgNotify> = {
  encode(message: MsgNotify, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.groupId !== "") {
      writer.uint32(10).string(message.groupId);
    }
    if (message.syncSeqId !== "0") {
      writer.uint32(16).uint64(message.syncSeqId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgNotify {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgNotify();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.groupId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.syncSeqId = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgNotify {
    return {
      groupId: isSet(object.groupId) ? globalThis.String(object.groupId) : "",
      syncSeqId: isSet(object.syncSeqId) ? globalThis.String(object.syncSeqId) : "0",
    };
  },

  toJSON(message: MsgNotify): unknown {
    const obj: any = {};
    if (message.groupId !== "") {
      obj.groupId = message.groupId;
    }
    if (message.syncSeqId !== "0") {
      obj.syncSeqId = message.syncSeqId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgNotify>, I>>(base?: I): MsgNotify {
    return MsgNotify.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgNotify>, I>>(object: I): MsgNotify {
    const message = createBaseMsgNotify();
    message.groupId = object.groupId ?? "";
    message.syncSeqId = object.syncSeqId ?? "0";
    return message;
  },
};

function createBaseAuthReq(): AuthReq {
  return { deviceType: "", deviceId: "", jwt: "", supportedVersions: [] };
}

export const AuthReq: MessageFns<AuthReq> = {
  encode(message: AuthReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceType !== "") {
      writer.uint32(10).string(message.deviceType);
    }
    if (message.deviceId !== "") {
      writer.uint32(18).string(message.deviceId);
    }
    if (message.jwt !== "") {
      writer.uint32(26).string(message.jwt);
    }
    writer.uint32(34).fork();
    for (const v of message.supportedVersions) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jwt = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.supportedVersions.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.supportedVersions.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthReq {
    return {
      deviceType: isSet(object.deviceType) ? globalThis.String(object.deviceType) : "",
      deviceId: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
      jwt: isSet(object.jwt) ? globalThis.String(object.jwt) : "",
      supportedVersions: globalThis.Array.isArray(object?.supportedVersions)
        ? object.supportedVersions.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: AuthReq): unknown {
    const obj: any = {};
    if (message.deviceType !== "") {
      obj.deviceType = message.deviceType;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.jwt !== "") {
      obj.jwt = message.jwt;
    }
    if (message.supportedVersions?.length) {
      obj.supportedVersions = message.supportedVersions.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthReq>, I>>(base?: I): AuthReq {
    return AuthReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthReq>, I>>(object: I): AuthReq {
    const message = createBaseAuthReq();
    message.deviceType = object.deviceType ?? "";
    message.deviceId = object.deviceId ?? "";
    message.jwt = object.jwt ?? "";
    message.supportedVersions = object.supportedVersions?.map((e) => e) || [];
    return message;
  },
};

function createBaseAuthAck(): AuthAck {
  return { userId: "" };
}

export const AuthAck: MessageFns<AuthAck> = {
  encode(message: AuthAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthAck {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: AuthAck): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthAck>, I>>(base?: I): AuthAck {
    return AuthAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthAck>, I>>(object: I): AuthAck {
    const message = createBaseAuthAck();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseReadReceipt(): ReadReceipt {
  return { groupId: "", syncSeqId: "0" };
}

export const ReadReceipt: MessageFns<ReadReceipt> = {
  encode(message: ReadReceipt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.groupId !== "") {
      writer.uint32(10).string(message.groupId);
    }
    if (message.syncSeqId !== "0") {
      writer.uint32(16).uint64(message.syncSeqId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadReceipt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadReceipt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.groupId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.syncSeqId = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadReceipt {
    return {
      groupId: isSet(object.groupId) ? globalThis.String(object.groupId) : "",
      syncSeqId: isSet(object.syncSeqId) ? globalThis.String(object.syncSeqId) : "0",
    };
  },

  toJSON(message: ReadReceipt): unknown {
    const obj: any = {};
    if (message.groupId !== "") {
      obj.groupId = message.groupId;
    }
    if (message.syncSeqId !== "0") {
      obj.syncSeqId = message.syncSeqId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadReceipt>, I>>(base?: I): ReadReceipt {
    return ReadReceipt.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadReceipt>, I>>(object: I): ReadReceipt {
    const message = createBaseReadReceipt();
    message.groupId = object.groupId ?? "";
    message.syncSeqId = object.syncSeqId ?? "0";
    return message;
  },
};

function createBaseExceptionAck(): ExceptionAck {
  return { errorCode: 0, message: "", timestamp: "", serverSupportedVersions: [] };
}

export const ExceptionAck: MessageFns<ExceptionAck> = {
  encode(message: ExceptionAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.errorCode !== 0) {
      writer.uint32(8).int32(message.errorCode);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.timestamp !== "") {
      writer.uint32(26).string(message.timestamp);
    }
    writer.uint32(34).fork();
    for (const v of message.serverSupportedVersions) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExceptionAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExceptionAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 4: {
          if (tag === 32) {
            message.serverSupportedVersions.push(reader.int32());

            continue;
          }

          if (tag === 34) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.serverSupportedVersions.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExceptionAck {
    return {
      errorCode: isSet(object.errorCode) ? globalThis.Number(object.errorCode) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      serverSupportedVersions: globalThis.Array.isArray(object?.serverSupportedVersions)
        ? object.serverSupportedVersions.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: ExceptionAck): unknown {
    const obj: any = {};
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.serverSupportedVersions?.length) {
      obj.serverSupportedVersions = message.serverSupportedVersions.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExceptionAck>, I>>(base?: I): ExceptionAck {
    return ExceptionAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExceptionAck>, I>>(object: I): ExceptionAck {
    const message = createBaseExceptionAck();
    message.errorCode = object.errorCode ?? 0;
    message.message = object.message ?? "";
    message.timestamp = object.timestamp ?? "";
    message.serverSupportedVersions = object.serverSupportedVersions?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
